# Use Python 3.9 slim image as the base
FROM python:3.9-slim

# Set the working directory inside the container
WORKDIR /workspace

# Copy all the files from the current directory into the container
COPY . .

# Install necessary build tools and dependencies for Python packages
RUN apt-get clean && rm -rf /var/lib/apt/lists/* \
    && apt-get update && apt-get install -y --fix-missing \
    build-essential \
    libssl-dev \
    libffi-dev \
    python3-dev \
    && apt-get clean && rm -rf /var/lib/apt/lists/*

# Install Python dependencies listed in the requirements.txt
RUN pip install --no-cache-dir -r requirements.txt

# Expose port 80 (optional if running a web app)
EXPOSE 80

# Set an environment variable
ENV NAME=MLOpsLab

# Command to run when the container starts (train.py script)
CMD ["python", "train.py"]

